// Static and Curated Locations Dataset for Route Connect
// Contains verified geographic locations: cities, towns, villages, mandals, bus stations, railway stations, airports, and landmarks.
// Compliant with open data licensing and authoritative administrative boundaries.

export const STATIC_LOCATIONS = [
  // West Godavari (AP) - Villages, Towns, Stations & Bus Stops
  { id: 'bhimavaram', name: 'Bhimavaram', latitude: 16.5449, longitude: 81.5224, mandal: 'Bhimavaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'city', code: 'BVRM' },
  { id: 'bhimavaram railway station', name: 'Bhimavaram Railway Station', latitude: 16.5410, longitude: 81.5150, mandal: 'Bhimavaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'BVRM' },
  { id: 'bhimavaram junction', name: 'Bhimavaram Junction', latitude: 16.5410, longitude: 81.5150, mandal: 'Bhimavaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'BVRM' },
  { id: 'bhimavaram town railway station', name: 'Bhimavaram Town Railway Station', latitude: 16.5360, longitude: 81.5280, mandal: 'Bhimavaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'BVRT' },
  { id: 'bhimavaram bus station', name: 'Bhimavaram Bus Station', latitude: 16.5490, longitude: 81.5280, mandal: 'Bhimavaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  
  // Rural Villages in West Godavari
  { id: 'undi', name: 'Undi', latitude: 16.6025, longitude: 81.4616, mandal: 'Undi', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village', code: 'UNDI' },
  { id: 'undi railway station', name: 'Undi Railway Station', latitude: 16.6010, longitude: 81.4600, mandal: 'Undi', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'UNDI' },
  { id: 'undi (chinna mandal)', name: 'Undi (Chinna Mandal)', latitude: 14.5020, longitude: 77.8010, mandal: 'Chinna Mandal', district: 'Sri Sathya Sai', state: 'Andhra Pradesh', type: 'village' },
  { id: 'kalla', name: 'Kalla', latitude: 16.5515, longitude: 81.4550, mandal: 'Kalla', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village' },
  { id: 'kalla bus stop', name: 'Kalla Bus Stop', latitude: 16.5510, longitude: 81.4540, mandal: 'Kalla', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'veeravasaram', name: 'Veeravasaram', latitude: 16.5160, longitude: 81.6030, mandal: 'Veeravasaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village', code: 'VVM' },
  { id: 'veeravasaram railway station', name: 'Veeravasaram Railway Station', latitude: 16.5170, longitude: 81.6040, mandal: 'Veeravasaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'VVM' },
  { id: 'mogalthur', name: 'Mogalthur', latitude: 16.4170, longitude: 81.5975, mandal: 'Mogalthur', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village' },
  { id: 'penugonda', name: 'Penugonda', latitude: 16.6310, longitude: 81.7240, mandal: 'Penugonda', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village' },
  { id: 'attili', name: 'Attili', latitude: 16.6890, longitude: 81.5980, mandal: 'Attili', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village', code: 'AL' },
  { id: 'attili railway station', name: 'Attili Railway Station', latitude: 16.6880, longitude: 81.5970, mandal: 'Attili', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'AL' },
  { id: 'ganapavaram', name: 'Ganapavaram', latitude: 16.6912, longitude: 81.4880, mandal: 'Ganapavaram', district: 'Eluru', state: 'Andhra Pradesh', type: 'village' },
  { id: 'pippara', name: 'Pippara', latitude: 16.7120, longitude: 81.5540, mandal: 'Ganapavaram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village' },
  { id: 'maruteru', name: 'Maruteru', latitude: 16.6210, longitude: 81.7450, mandal: 'Penugonda', district: 'West Godavari', state: 'Andhra Pradesh', type: 'village' },
  { id: 'peravali', name: 'Peravali', latitude: 16.7600, longitude: 81.7800, mandal: 'Peravali', district: 'East Godavari', state: 'Andhra Pradesh', type: 'village' },
  
  // Towns in West Godavari & Eluru
  { id: 'akividu', name: 'Akividu', latitude: 16.6015, longitude: 81.3787, mandal: 'Akividu', district: 'West Godavari', state: 'Andhra Pradesh', type: 'town', code: 'AKVD' },
  { id: 'akividu railway station', name: 'Akividu Railway Station', latitude: 16.6010, longitude: 81.3780, mandal: 'Akividu', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'AKVD' },
  { id: 'akividu bus station', name: 'Akividu Bus Station', latitude: 16.6025, longitude: 81.3800, mandal: 'Akividu', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'palakollu', name: 'Palakollu', latitude: 16.5262, longitude: 81.7282, mandal: 'Palakollu', district: 'West Godavari', state: 'Andhra Pradesh', type: 'town', code: 'PKO' },
  { id: 'palakollu railway station', name: 'Palakollu Railway Station', latitude: 16.5250, longitude: 81.7270, mandal: 'Palakollu', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'PKO' },
  { id: 'palakollu bus station', name: 'Palakollu Bus Station', latitude: 16.5270, longitude: 81.7290, mandal: 'Palakollu', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'narasapuram', name: 'Narasapuram', latitude: 16.4385, longitude: 81.7016, mandal: 'Narasapuram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'town', code: 'NS' },
  { id: 'narsapur railway station', name: 'Narsapur Railway Station', latitude: 16.4380, longitude: 81.6970, mandal: 'Narasapuram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'NS' },
  { id: 'narasapuram bus stand', name: 'Narasapuram Bus Stand', latitude: 16.4390, longitude: 81.7020, mandal: 'Narasapuram', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'tanuku', name: 'Tanuku', latitude: 16.7565, longitude: 81.6811, mandal: 'Tanuku', district: 'West Godavari', state: 'Andhra Pradesh', type: 'town', code: 'TNKU' },
  { id: 'tanuku railway station', name: 'Tanuku Railway Station', latitude: 16.7550, longitude: 81.6800, mandal: 'Tanuku', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'TNKU' },
  { id: 'tanuku bus station', name: 'Tanuku Bus Station', latitude: 16.7580, longitude: 81.6830, mandal: 'Tanuku', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'tadepalligudem', name: 'Tadepalligudem', latitude: 16.8142, longitude: 81.5267, mandal: 'Tadepalligudem', district: 'West Godavari', state: 'Andhra Pradesh', type: 'town', code: 'TDD' },
  { id: 'tadepalligudem railway station', name: 'Tadepalligudem Railway Station', latitude: 16.8130, longitude: 81.5250, mandal: 'Tadepalligudem', district: 'West Godavari', state: 'Andhra Pradesh', type: 'station', code: 'TDD' },
  { id: 'tadepalligudem bus station', name: 'Tadepalligudem Bus Station', latitude: 16.8150, longitude: 81.5280, mandal: 'Tadepalligudem', district: 'West Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'eluru', name: 'Eluru', latitude: 16.7107, longitude: 81.0952, mandal: 'Eluru', district: 'Eluru', state: 'Andhra Pradesh', type: 'city', code: 'EE' },
  { id: 'eluru railway station', name: 'Eluru Railway Station', latitude: 16.7090, longitude: 81.0940, mandal: 'Eluru', district: 'Eluru', state: 'Andhra Pradesh', type: 'station', code: 'EE' },
  { id: 'eluru bus station', name: 'Eluru Bus Station', latitude: 16.7120, longitude: 81.0980, mandal: 'Eluru', district: 'Eluru', state: 'Andhra Pradesh', type: 'bus' },

  // NTR & Krishna District
  { id: 'vijayawada', name: 'Vijayawada', latitude: 16.5062, longitude: 80.6480, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'city', code: 'BZA' },
  { id: 'vijayawada railway station', name: 'Vijayawada Railway Station', latitude: 16.5180, longitude: 80.6200, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'station', code: 'BZA' },
  { id: 'vijayawada junction', name: 'Vijayawada Junction', latitude: 16.5180, longitude: 80.6200, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'station', code: 'BZA' },
  { id: 'vijayawada bus station', name: 'Vijayawada Bus Station', latitude: 16.5120, longitude: 80.6280, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'pandit nehru bus station', name: 'Pandit Nehru Bus Station', latitude: 16.5120, longitude: 80.6280, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'vijayawada airport', name: 'Vijayawada Airport', latitude: 16.5310, longitude: 80.7960, mandal: 'Gannavaram', district: 'NTR', state: 'Andhra Pradesh', type: 'airport', code: 'VGA' },
  { id: 'kanaka durga temple', name: 'Kanaka Durga Temple', latitude: 16.5152, longitude: 80.6050, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'landmark' },
  { id: 'vijayawada final destination', name: 'Vijayawada Final Destination', latitude: 16.5020, longitude: 80.6400, mandal: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', type: 'landmark' },
  { id: 'ibrahimpatnam', name: 'Ibrahimpatnam', latitude: 16.5898, longitude: 80.5230, mandal: 'Ibrahimpatnam', district: 'NTR', state: 'Andhra Pradesh', type: 'town' },
  { id: 'nandigama', name: 'Nandigama', latitude: 16.7847, longitude: 80.2917, mandal: 'Nandigama', district: 'NTR', state: 'Andhra Pradesh', type: 'town' },
  { id: 'gudivada', name: 'Gudivada', latitude: 16.4410, longitude: 80.9930, mandal: 'Gudivada', district: 'Krishna', state: 'Andhra Pradesh', type: 'town', code: 'GDV' },
  { id: 'gudivada railway station', name: 'Gudivada Railway Station', latitude: 16.4400, longitude: 80.9920, mandal: 'Gudivada', district: 'Krishna', state: 'Andhra Pradesh', type: 'station', code: 'GDV' },
  { id: 'machilipatnam', name: 'Machilipatnam', latitude: 16.1875, longitude: 81.1390, mandal: 'Machilipatnam', district: 'Krishna', state: 'Andhra Pradesh', type: 'city', code: 'MTM' },
  { id: 'machilipatnam railway station', name: 'Machilipatnam Railway Station', latitude: 16.1860, longitude: 81.1380, mandal: 'Machilipatnam', district: 'Krishna', state: 'Andhra Pradesh', type: 'station', code: 'MTM' },
  { id: 'challapalli', name: 'Challapalli', latitude: 16.1185, longitude: 80.9310, mandal: 'Challapalli', district: 'Krishna', state: 'Andhra Pradesh', type: 'village' },
  { id: 'vuyyuru', name: 'Vuyyuru', latitude: 16.3685, longitude: 80.8490, mandal: 'Vuyyuru', district: 'Krishna', state: 'Andhra Pradesh', type: 'town' },
  { id: 'pamarru', name: 'Pamarru', latitude: 16.3315, longitude: 80.9630, mandal: 'Pamarru', district: 'Krishna', state: 'Andhra Pradesh', type: 'town' },

  // Guntur, Palnadu & Bapatla
  { id: 'guntur', name: 'Guntur', latitude: 16.3067, longitude: 80.4365, mandal: 'Guntur', district: 'Guntur', state: 'Andhra Pradesh', type: 'city', code: 'GNT' },
  { id: 'guntur railway station', name: 'Guntur Railway Station', latitude: 16.3012, longitude: 80.4440, mandal: 'Guntur', district: 'Guntur', state: 'Andhra Pradesh', type: 'station', code: 'GNT' },
  { id: 'guntur bus station', name: 'Guntur Bus Station', latitude: 16.3050, longitude: 80.4500, mandal: 'Guntur', district: 'Guntur', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'tenali', name: 'Tenali', latitude: 16.2396, longitude: 80.6467, mandal: 'Tenali', district: 'Guntur', state: 'Andhra Pradesh', type: 'city', code: 'TEL' },
  { id: 'tenali railway station', name: 'Tenali Railway Station', latitude: 16.2380, longitude: 80.6450, mandal: 'Tenali', district: 'Guntur', state: 'Andhra Pradesh', type: 'station', code: 'TEL' },
  { id: 'mangalagiri', name: 'Mangalagiri', latitude: 16.4326, longitude: 80.5658, mandal: 'Mangalagiri', district: 'Guntur', state: 'Andhra Pradesh', type: 'town', code: 'MAG' },
  { id: 'amaravati', name: 'Amaravati', latitude: 16.5744, longitude: 80.3575, mandal: 'Amaravati', district: 'Guntur', state: 'Andhra Pradesh', type: 'village' },
  { id: 'bapatla', name: 'Bapatla', latitude: 15.9042, longitude: 80.4674, mandal: 'Bapatla', district: 'Bapatla', state: 'Andhra Pradesh', type: 'town', code: 'BPP' },
  { id: 'chirala', name: 'Chirala', latitude: 15.8236, longitude: 80.3524, mandal: 'Chirala', district: 'Bapatla', state: 'Andhra Pradesh', type: 'town', code: 'CLX' },

  // Narasaraopet -> Ongole Corridor Villages and Towns
  { id: 'narasaraopet', name: 'Narasaraopet', latitude: 16.2359, longitude: 80.0499, mandal: 'Narasaraopet', district: 'Palnadu', state: 'Andhra Pradesh', type: 'city', code: 'NRT' },
  { id: 'narasaraopet bus station', name: 'Narasaraopet Bus Station', latitude: 16.2380, longitude: 80.0510, mandal: 'Narasaraopet', district: 'Palnadu', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'narasaraopet railway station', name: 'Narasaraopet Railway Station', latitude: 16.2330, longitude: 80.0460, mandal: 'Narasaraopet', district: 'Palnadu', state: 'Andhra Pradesh', type: 'station', code: 'NRT' },
  { id: 'mulakalur', name: 'Mulakalur', latitude: 16.2080, longitude: 80.0910, mandal: 'Narasaraopet', district: 'Palnadu', state: 'Andhra Pradesh', type: 'village' },
  { id: 'rompicherla', name: 'Rompicherla', latitude: 16.1750, longitude: 80.0520, mandal: 'Rompicherla', district: 'Palnadu', state: 'Andhra Pradesh', type: 'village' },
  { id: 'santhamaguluru', name: 'Santhamaguluru', latitude: 16.0350, longitude: 80.0150, mandal: 'Santhamaguluru', district: 'Bapatla', state: 'Andhra Pradesh', type: 'village' },
  { id: 'kotikalapudi', name: 'Kotikalapudi', latitude: 15.9320, longitude: 79.9950, mandal: 'Addanki', district: 'Bapatla', state: 'Andhra Pradesh', type: 'village' },
  { id: 'kakani', name: 'Kakani', latitude: 16.1950, longitude: 80.1200, mandal: 'Narasaraopet', district: 'Palnadu', state: 'Andhra Pradesh', type: 'village' },
  { id: 'nadendla', name: 'Nadendla', latitude: 16.1550, longitude: 80.1450, mandal: 'Nadendla', district: 'Palnadu', state: 'Andhra Pradesh', type: 'village' },
  { id: 'chilakaluripeta', name: 'Chilakaluripeta', latitude: 16.0892, longitude: 80.1672, mandal: 'Chilakaluripeta', district: 'Palnadu', state: 'Andhra Pradesh', type: 'town' },
  { id: 'chilakaluripeta bus stand', name: 'Chilakaluripeta Bus Stand', latitude: 16.0880, longitude: 80.1660, mandal: 'Chilakaluripeta', district: 'Palnadu', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'purushothapatnam', name: 'Purushothapatnam', latitude: 16.0420, longitude: 80.1400, mandal: 'Chilakaluripeta', district: 'Palnadu', state: 'Andhra Pradesh', type: 'village' },
  { id: 'martur', name: 'Martur', latitude: 15.9890, longitude: 80.1150, mandal: 'Martur', district: 'Bapatla', state: 'Andhra Pradesh', type: 'village' },
  { id: 'addanki', name: 'Addanki', latitude: 15.8167, longitude: 79.9833, mandal: 'Addanki', district: 'Bapatla', state: 'Andhra Pradesh', type: 'town' },
  { id: 'addanki bus stand', name: 'Addanki Bus Stand', latitude: 15.8150, longitude: 79.9820, mandal: 'Addanki', district: 'Bapatla', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'medarmetla', name: 'Medarmetla', latitude: 15.7550, longitude: 80.0120, mandal: 'Korisapadu', district: 'Bapatla', state: 'Andhra Pradesh', type: 'village' },
  { id: 'korisapadu', name: 'Korisapadu', latitude: 15.6980, longitude: 80.0250, mandal: 'Korisapadu', district: 'Bapatla', state: 'Andhra Pradesh', type: 'village' },
  { id: 'maddipadu', name: 'Maddipadu', latitude: 15.6120, longitude: 80.0410, mandal: 'Maddipadu', district: 'Prakasam', state: 'Andhra Pradesh', type: 'village' },
  { id: 'maddipadu bus stop', name: 'Maddipadu Bus Stop', latitude: 15.6130, longitude: 80.0420, mandal: 'Maddipadu', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'ongole', name: 'Ongole', latitude: 15.5057, longitude: 80.0499, mandal: 'Ongole', district: 'Prakasam', state: 'Andhra Pradesh', type: 'city', code: 'OGL' },
  { id: 'ongole bus stand', name: 'Ongole Bus Stand', latitude: 15.5030, longitude: 80.0480, mandal: 'Ongole', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'ongole railway station', name: 'Ongole Railway Station', latitude: 15.5110, longitude: 80.0540, mandal: 'Ongole', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'OGL' },
  { id: 'kanigiri', name: 'Kanigiri', latitude: 15.4000, longitude: 79.5100, mandal: 'Kanigiri', district: 'Prakasam', state: 'Andhra Pradesh', type: 'town' },
  { id: 'kanigiri bus stand', name: 'Kanigiri Bus Stand', latitude: 15.3990, longitude: 79.5110, mandal: 'Kanigiri', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'village x', name: 'Village X', latitude: 15.5330, longitude: 80.0310, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'village' },
  { id: 'village x bus stop', name: 'Village X Bus Stop', latitude: 15.5180, longitude: 80.0460, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'village y', name: 'Village Y', latitude: 15.5600, longitude: 80.0350, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'village' },
  { id: 'bus stop z', name: 'Bus Stop Z', latitude: 15.5450, longitude: 80.0410, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },

  // Multi-Modal Network Benchmark Locations (Village A/B, Town B/C/X/Y, City B/C/D, Stations)
  { id: 'village a', name: 'Village A', latitude: 15.6500, longitude: 80.1200, mandal: 'Village A Mandal', district: 'Prakasam', state: 'Andhra Pradesh', type: 'village' },
  { id: 'village a bus stop', name: 'Village A Bus Stop', latitude: 15.6420, longitude: 80.1150, mandal: 'Village A Mandal', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'village b', name: 'Village B', latitude: 15.6900, longitude: 80.0900, mandal: 'Village B Mandal', district: 'Prakasam', state: 'Andhra Pradesh', type: 'village' },
  { id: 'town b', name: 'Town B', latitude: 15.7200, longitude: 80.0400, mandal: 'Town B', district: 'Prakasam', state: 'Andhra Pradesh', type: 'town' },
  { id: 'town b bus stand', name: 'Town B Bus Stand', latitude: 15.7210, longitude: 80.0410, mandal: 'Town B', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'town b railway station', name: 'Town B Railway Station', latitude: 15.7350, longitude: 80.0550, mandal: 'Town B', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'TWNB' },
  { id: 'town c', name: 'Town C', latitude: 15.8000, longitude: 80.0100, mandal: 'Town C', district: 'Bapatla', state: 'Andhra Pradesh', type: 'town' },
  { id: 'town c bus stand', name: 'Town C Bus Stand', latitude: 15.7990, longitude: 80.0090, mandal: 'Town C', district: 'Bapatla', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'town c railway station', name: 'Town C Railway Station', latitude: 15.8150, longitude: 80.0250, mandal: 'Town C', district: 'Bapatla', state: 'Andhra Pradesh', type: 'station', code: 'TWNC' },
  { id: 'railway station d', name: 'Railway Station D', latitude: 15.5350, longitude: 80.0420, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'RSD' },
  { id: 'railway station y', name: 'Railway Station Y', latitude: 15.5150, longitude: 80.0600, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'RSY' },
  { id: 'city d', name: 'City D', latitude: 15.5000, longitude: 80.0500, mandal: 'Ongole Urban', district: 'Prakasam', state: 'Andhra Pradesh', type: 'city', code: 'CTYD' },
  { id: 'city d bus stand', name: 'City D Bus Stand', latitude: 15.5020, longitude: 80.0490, mandal: 'Ongole Urban', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'city d railway station', name: 'City D Railway Station', latitude: 15.5050, longitude: 80.0530, mandal: 'Ongole Urban', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'CTYD' },
  { id: 'city c', name: 'City C', latitude: 15.4800, longitude: 80.0700, mandal: 'Ongole Urban', district: 'Prakasam', state: 'Andhra Pradesh', type: 'city', code: 'CTYC' },
  { id: 'city c railway station', name: 'City C Railway Station', latitude: 15.4820, longitude: 80.0680, mandal: 'Ongole Urban', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'CTYC' },
  { id: 'town x', name: 'Town X', latitude: 15.7500, longitude: 80.0500, mandal: 'Town X', district: 'Prakasam', state: 'Andhra Pradesh', type: 'town' },
  { id: 'town x bus stand', name: 'Town X Bus Stand', latitude: 15.7520, longitude: 80.0520, mandal: 'Town X', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'town x railway station', name: 'Town X Railway Station', latitude: 15.7350, longitude: 80.0350, mandal: 'Town X', district: 'Prakasam', state: 'Andhra Pradesh', type: 'station', code: 'TWNX' },
  { id: 'town y', name: 'Town Y', latitude: 15.6800, longitude: 79.9200, mandal: 'Town Y', district: 'Prakasam', state: 'Andhra Pradesh', type: 'town' },
  { id: 'town y bus stand', name: 'Town Y Bus Stand', latitude: 15.6810, longitude: 79.9210, mandal: 'Town Y', district: 'Prakasam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'railway station z', name: 'Railway Station Z', latitude: 15.7200, longitude: 80.1500, mandal: 'Addanki', district: 'Bapatla', state: 'Andhra Pradesh', type: 'station', code: 'RSZ' },
  { id: 'railway station x', name: 'Railway Station X', latitude: 15.7100, longitude: 80.1000, mandal: 'Korisapadu', district: 'Bapatla', state: 'Andhra Pradesh', type: 'station', code: 'RSX' },
  { id: 'city b', name: 'City B', latitude: 15.9000, longitude: 80.4500, mandal: 'Bapatla', district: 'Bapatla', state: 'Andhra Pradesh', type: 'city', code: 'CTYB' },
  { id: 'city b railway station', name: 'City B Railway Station', latitude: 15.8980, longitude: 80.4480, mandal: 'Bapatla', district: 'Bapatla', state: 'Andhra Pradesh', type: 'station', code: 'CTYB' },
  { id: 'city b bus stand', name: 'City B Bus Stand', latitude: 15.9020, longitude: 80.4520, mandal: 'Bapatla', district: 'Bapatla', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'final destination', name: 'Final Destination', latitude: 15.5200, longitude: 80.0800, mandal: 'Ongole Rural', district: 'Prakasam', state: 'Andhra Pradesh', type: 'landmark' },

  // East Godavari & Kakinada
  { id: 'rajahmundry', name: 'Rajahmundry', latitude: 17.0005, longitude: 81.7835, mandal: 'Rajahmundry', district: 'East Godavari', state: 'Andhra Pradesh', type: 'city', code: 'RJY' },
  { id: 'rajahmundry railway station', name: 'Rajahmundry Railway Station', latitude: 16.9912, longitude: 81.7790, mandal: 'Rajahmundry', district: 'East Godavari', state: 'Andhra Pradesh', type: 'station', code: 'RJY' },
  { id: 'rajahmundry bus station', name: 'Rajahmundry Bus Station', latitude: 17.0010, longitude: 81.7890, mandal: 'Rajahmundry', district: 'East Godavari', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'kovvur', name: 'Kovvur', latitude: 17.0145, longitude: 81.7240, mandal: 'Kovvur', district: 'East Godavari', state: 'Andhra Pradesh', type: 'town', code: 'KVR' },
  { id: 'kakinada', name: 'Kakinada', latitude: 16.9890, longitude: 82.2474, mandal: 'Kakinada', district: 'Kakinada', state: 'Andhra Pradesh', type: 'city', code: 'CCT' },
  { id: 'samalkot', name: 'Samalkot', latitude: 17.0545, longitude: 82.1690, mandal: 'Samalkot', district: 'Kakinada', state: 'Andhra Pradesh', type: 'town', code: 'SLO' },

  // Visakhapatnam & North Coastal AP
  { id: 'visakhapatnam', name: 'Visakhapatnam', latitude: 17.6868, longitude: 83.2185, mandal: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh', type: 'city', code: 'VSKP' },
  { id: 'visakhapatnam railway station', name: 'Visakhapatnam Railway Station', latitude: 17.6912, longitude: 83.2986, mandal: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh', type: 'station', code: 'VSKP' },
  { id: 'dwaraka bus complex', name: 'Dwaraka Bus Complex', latitude: 17.7215, longitude: 83.3012, mandal: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'visakhapatnam airport', name: 'Visakhapatnam Airport', latitude: 17.7210, longitude: 83.2240, mandal: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh', type: 'airport', code: 'VTZ' },
  { id: 'gajuwaka', name: 'Gajuwaka', latitude: 17.6896, longitude: 83.1878, mandal: 'Gajuwaka', district: 'Visakhapatnam', state: 'Andhra Pradesh', type: 'town' },
  { id: 'anakapalli', name: 'Anakapalli', latitude: 17.6914, longitude: 83.0039, mandal: 'Anakapalli', district: 'Anakapalli', state: 'Andhra Pradesh', type: 'town', code: 'AKP' },
  { id: 'tuni', name: 'Tuni', latitude: 17.3582, longitude: 82.5516, mandal: 'Tuni', district: 'Kakinada', state: 'Andhra Pradesh', type: 'town', code: 'TUNI' },

  // South AP (Rayalaseema & Nellore)
  { id: 'nellore', name: 'Nellore', latitude: 14.4426, longitude: 79.9865, mandal: 'Nellore', district: 'SPS Nellore', state: 'Andhra Pradesh', type: 'city', code: 'NLR' },
  { id: 'nellore railway station', name: 'Nellore Railway Station', latitude: 14.4430, longitude: 79.9870, mandal: 'Nellore', district: 'SPS Nellore', state: 'Andhra Pradesh', type: 'station', code: 'NLR' },
  { id: 'kurnool', name: 'Kurnool', latitude: 15.8281, longitude: 78.0373, mandal: 'Kurnool', district: 'Kurnool', state: 'Andhra Pradesh', type: 'city', code: 'KRNT' },
  { id: 'tirupati', name: 'Tirupati', latitude: 13.6288, longitude: 79.4192, mandal: 'Tirupati', district: 'Tirupati', state: 'Andhra Pradesh', type: 'city', code: 'TPTY' },
  { id: 'tirupati railway station', name: 'Tirupati Railway Station', latitude: 13.6275, longitude: 79.4168, mandal: 'Tirupati', district: 'Tirupati', state: 'Andhra Pradesh', type: 'station', code: 'TPTY' },
  { id: 'tirupati bus station', name: 'Tirupati Bus Station', latitude: 13.6260, longitude: 79.4215, mandal: 'Tirupati', district: 'Tirupati', state: 'Andhra Pradesh', type: 'bus' },
  { id: 'renigunta', name: 'Renigunta', latitude: 13.6385, longitude: 79.5160, mandal: 'Renigunta', district: 'Tirupati', state: 'Andhra Pradesh', type: 'town', code: 'RU' },
  { id: 'renigunta railway station', name: 'Renigunta Railway Station', latitude: 13.6380, longitude: 79.5150, mandal: 'Renigunta', district: 'Tirupati', state: 'Andhra Pradesh', type: 'station', code: 'RU' },

  // Interstate & Major National Hubs
  { id: 'hyderabad', name: 'Hyderabad', latitude: 17.3850, longitude: 78.4867, mandal: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', type: 'city', code: 'HYB' },
  { id: 'secunderabad railway station', name: 'Secunderabad Railway Station', latitude: 17.4344, longitude: 78.5015, mandal: 'Secunderabad', district: 'Hyderabad', state: 'Telangana', type: 'station', code: 'SC' },
  { id: 'mgbs bus station', name: 'Mahatma Gandhi Bus Station', latitude: 17.3780, longitude: 78.4820, mandal: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', type: 'bus' },
  { id: 'rajiv gandhi international airport', name: 'Rajiv Gandhi International Airport', latitude: 17.2403, longitude: 78.4294, mandal: 'Shamshabad', district: 'Rangareddy', state: 'Telangana', type: 'airport', code: 'HYD' },
  { id: 'charminar', name: 'Charminar', latitude: 17.3616, longitude: 78.4747, mandal: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', type: 'landmark' },
  { id: 'bengaluru', name: 'Bengaluru', latitude: 12.9716, longitude: 77.5946, mandal: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', type: 'city', code: 'SBC' },
  { id: 'bengaluru railway station', name: 'KSR Bengaluru Railway Station', latitude: 12.9780, longitude: 77.5690, mandal: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', type: 'station', code: 'SBC' },
  { id: 'chennai', name: 'Chennai', latitude: 13.0827, longitude: 80.2707, mandal: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', type: 'city', code: 'MAS' },
  { id: 'chennai central', name: 'Chennai Central Railway Station', latitude: 13.0830, longitude: 80.2750, mandal: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', type: 'station', code: 'MAS' },
  { id: 'mumbai', name: 'Mumbai', latitude: 19.0760, longitude: 72.8777, mandal: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', type: 'city', code: 'CSMT' },
  { id: 'csmt railway station', name: 'Chhatrapati Shivaji Maharaj Terminus', latitude: 18.9400, longitude: 72.8350, mandal: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', type: 'station', code: 'CSMT' },
  { id: 'pune', name: 'Pune', latitude: 18.5204, longitude: 73.8567, mandal: 'Pune', district: 'Pune', state: 'Maharashtra', type: 'city', code: 'PUNE' },
  { id: 'delhi', name: 'Delhi', latitude: 28.6139, longitude: 77.2090, mandal: 'Delhi', district: 'Delhi', state: 'Delhi NCR', type: 'city', code: 'NDLS' },
  { id: 'new delhi railway station', name: 'New Delhi Railway Station', latitude: 28.6420, longitude: 77.2200, mandal: 'Delhi', district: 'Delhi', state: 'Delhi NCR', type: 'station', code: 'NDLS' },
  { id: 'kolkata', name: 'Kolkata', latitude: 22.5726, longitude: 88.3639, mandal: 'Kolkata', district: 'Kolkata', state: 'West Bengal', type: 'city', code: 'HWH' },
  { id: 'howrah railway station', name: 'Howrah Railway Station', latitude: 22.5830, longitude: 88.3420, mandal: 'Howrah', district: 'Howrah', state: 'West Bengal', type: 'station', code: 'HWH' },

  // Commercial Domestic & International Airports
  { id: 'hyderabad airport', name: 'Hyderabad Airport', latitude: 17.2403, longitude: 78.4294, mandal: 'Shamshabad', district: 'Rangareddy', state: 'Telangana', type: 'airport', code: 'HYD' },
  { id: 'bengaluru airport', name: 'Bengaluru Airport', latitude: 13.1986, longitude: 77.7066, mandal: 'Devanahalli', district: 'Bengaluru Rural', state: 'Karnataka', type: 'airport', code: 'BLR' },
  { id: 'kempegowda international airport', name: 'Kempegowda International Airport', latitude: 13.1986, longitude: 77.7066, mandal: 'Devanahalli', district: 'Bengaluru Rural', state: 'Karnataka', type: 'airport', code: 'BLR' },
  { id: 'chennai airport', name: 'Chennai Airport', latitude: 12.9941, longitude: 80.1709, mandal: 'Meenambakkam', district: 'Chennai', state: 'Tamil Nadu', type: 'airport', code: 'MAA' },
  { id: 'chennai international airport', name: 'Chennai International Airport', latitude: 12.9941, longitude: 80.1709, mandal: 'Meenambakkam', district: 'Chennai', state: 'Tamil Nadu', type: 'airport', code: 'MAA' },
  { id: 'tirupati airport', name: 'Tirupati Airport', latitude: 13.6325, longitude: 79.5433, mandal: 'Renigunta', district: 'Tirupati', state: 'Andhra Pradesh', type: 'airport', code: 'TIR' },
  { id: 'rajahmundry airport', name: 'Rajahmundry Airport', latitude: 17.1106, longitude: 81.8183, mandal: 'Madhurapudi', district: 'East Godavari', state: 'Andhra Pradesh', type: 'airport', code: 'RJA' },
  { id: 'delhi airport', name: 'Delhi Airport', latitude: 28.5562, longitude: 77.1000, mandal: 'Palam', district: 'South West Delhi', state: 'Delhi NCR', type: 'airport', code: 'DEL' },
  { id: 'indira gandhi international airport', name: 'Indira Gandhi International Airport', latitude: 28.5562, longitude: 77.1000, mandal: 'Palam', district: 'South West Delhi', state: 'Delhi NCR', type: 'airport', code: 'DEL' },
  { id: 'mumbai airport', name: 'Mumbai Airport', latitude: 19.0896, longitude: 72.8656, mandal: 'Santaruz', district: 'Mumbai Suburban', state: 'Maharashtra', type: 'airport', code: 'BOM' },
  { id: 'chhatrapati shivaji maharaj international airport', name: 'Chhatrapati Shivaji Maharaj International Airport', latitude: 19.0896, longitude: 72.8656, mandal: 'Santacruz', district: 'Mumbai Suburban', state: 'Maharashtra', type: 'airport', code: 'BOM' }
];
